version: "3.8"

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speakoai-telegram-bot
    command: python SpeakoAI/backend/telegram_bot.py
    volumes:
      - .:/app
    env_file:
      - SpeakoAI/.env
    environment:
      - PYTHONPATH=/app/SpeakoAI
    depends_on:
      - backend
    networks:
      - speakoai-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speakoai-backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - SpeakoAI/.env
    environment:
      - PYTHONPATH=/app/SpeakoAI
    depends_on:
      - db
      - ai-agent
    networks:
      - speakoai-network

  ai-agent:
    build:
      context: ./SpeakoAI/ai-agent
      dockerfile: Dockerfile
    container_name: speakoai-ai-agent
    ports:
      - "8085:8085"
    env_file:
      - ./SpeakoAI/.env
    networks:
      - speakoai-network

  frontend:
    build:
      context: ./SpeakoAIfront/speakoai
      dockerfile: Dockerfile
    container_name: speakoai-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - speakoai-network

  db:
    image: postgres:15
    container_name: speakoai-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: miniapp
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./SpeakoAI/populate_mock_data_fixed.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - speakoai-network

volumes:
  pgdata:

networks:
  speakoai-network:
    driver: bridge
