version: "3.8"

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speakoai-telegram-bot
    command: python SpeakoAI/backend/telegram_bot.py
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/SpeakoAI
    depends_on:
      - backend
    networks:
      - speakoai-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speakoai-backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/SpeakoAI
    depends_on:
      - db
      - ai-agent
    networks:
      - speakoai-network

  redis:
    image: redis:latest
    container_name: redis_ai_agent
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - speakoai-network


  ai-agent:
    build:
      context: ./SpeakoAI/ai-agent
      dockerfile: Dockerfile
    container_name: speakoai-ai-agent
    ports:
      - "8085:8085"
    env_file:
      - .env
    networks:
      - speakoai-network

    depends_on:
      - redis
  frontend:
    build:
      context: ./SpeakoAIfront/speakoai
      dockerfile: Dockerfile
    container_name: speakoai-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - speakoai-network

  db:
    image: postgres:15
    container_name: speakoai-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./SpeakoAI/populate_mock_data_fixed.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - speakoai-network

volumes:
  pgdata:
  redis_data:

networks:
  speakoai-network:
    driver: bridge
