[alembic]

script_location = %(here)s/alembic

prepend_sys_path = .


;
;# for running with docker
;;sqlalchemy.url = postgresql://postgres:admin1234@db:5432/miniapp
;
;#when we want to do the migration. (changes smth in models)
;sqlalchemy.url = postgresql://postgres:admin1234@localhost:5432/miniapp
;


[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
